name: Deployment
on:
  push:
    branches:
      [node2bun]

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          tags: minarin0179/madaminalink:latest
          push: true

  deploy:
    name: Deploy
    needs:
      - build_and_push
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull image
        run: docker pull minarin0179/madaminalink:latest

      - name: Deploy
        run: |
          docker compose -f production-compose.yml up -d

        #   自動で最新バージョンが取得されなさそう
        #   dcoker pullを実行 / metadataを取得して最新バージョンを取得する必要がある
        #   ref : 
            # - https://qiita.com/_kei_s/items/15c067090d5142648aac
            # - https://github.com/marketplace/actions/build-and-push-docker-images