name: Auto Deploy

on:
  push:
    branches:
      - master
      - node2bun #masterにマージしたら削除

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          tags: minarin0179/madaminalink:latest
          push: true

  deploy:
    name: Deploy
    needs:
      - build_and_push
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull image
        run: docker pull minarin0179/madaminalink:latest
      
      - name: Env
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "DEV_SERVER_ID=${{ secrets.DEV_SERVER_ID }}" >> .env
          echo "MONGODB=${{ secrets.MONGODB }}" >> .env
          echo "TZ=${{ secrets.TZ }}" >> .env

      - name: Deploy
        run: |
          echo "cd $(pwd) && docker compose up -d " | at -b 04:00
