name: Restart

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: restart
    runs-on: [self-hosted, my-runner]
    steps:
      - name: restart
        run: |
            docker compose restart bot
