name: Restart

on:
  schedule:
    - cron: '0 19 * * *' #毎日4:00(JST)
  workflow_dispatch:

jobs:
  deploy:
    name: restart
    runs-on: [self-hosted, my-runner]
    steps:
      - name: restart
        run: |
            docker compose up -d --force-recreate bot
